repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: my-postgres
    namespace: postgres
    chart: bitnami/postgresql
    values:
      - postgresql-values.yaml
  
  - name: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    values:
      - nginx-ingress-controller-values.yaml

  - name: backend
    namespace: app
    chart: ./backend-chart
    values:
      - ./backend-values.yaml

  - name: frontendk
    namespace: app
    chart: ./frontend-chart
    values:
      - ./frontend-values.yaml