apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}  # Base64 encode the username
  password: {{ .Values.postgresql.password | b64enc | quote }}  # Base64 encode the password